### ISSUE TITLE
45 page 테스트 code에서 assertNotNull()

### ISSUE THREAD

**Issue by hiyadana** [bjpublic/iseeapp#4]
45 page의 테스트 코드에 아래와 같이 되어있는데요. message 내용과 46 page의 설명과 다른것 같습니다.
assertNotNull("조회 결과 null", str);//null이 아님을 확인
이 부분은 null임을 확인하는 단언문(assertNull)이 적용되는게 맞아 보입니다.
확인 부탁드립니다.

**Comment by Charlezz** [comment]
제보 감사합니다. 재쇄하게 되면 수정하도록 하겠습니다.
