### ISSUE TITLE
코틀린으로 코드는 올려주실 생각 없으신가요?

### ISSUE THREAD

**Issue by greenhelix** [bjpublic/iseeapp#6]
코틀린으로 코드 올려주실 수 있나요?

**Comment by Charlezz** [comment]
책이 자바언어로 작성되어 출간되었기 때문에 코틀린으로 따로 작성할 계획은 없습니다.
https://open.kakao.com/o/gRToxkub
코틀린 및 기타 궁금한 부분은 오픈채팅방에 오셔서 질문하실 수 있습니다!
